name: Create Release

on:
  push:
    branches:
      - main

jobs:

  release:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - kubeconform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Release
      id: release
      uses: googleapis/release-please-action@v3
      with:
        release-type: simple
        path: ${{ matrix.directory }}

    - name: Construct Release Name
      id: ConstructReleaseName
      run: |
        RELEASE_NAME="${{ matrix.directory }}/${{ steps.release.outputs.release-version }}"
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release.outputs.release-version }}
        release_name: ${{ steps.ConstructReleaseName.outputs.RELEASE_NAME }}
        body: ${{ steps.release.outputs.release-notes }}
